/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_grayprocess2_ImageProc */

#ifndef _Included_com_example_grayprocess2_ImageProc
#define _Included_com_example_grayprocess2_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_grayprocess2_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_grayprocess2_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_example_grayprocess2_ImageProc
 * Method:    annProc
 * Signature: ([[FII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_grayprocess2_ImageProc_annProc
  (JNIEnv *, jclass, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
